services:
  backend:
    build: ./backend
    container_name: backend
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_NAME=database
    ports:
      - "3000:3000"
